_target_: sauce.standard.StandardModule
model_name: resnet
lr: 0.0001
wd: 0.0005
num_classes: ${data.metadata.n_classes}
distractors: ${data.metadata.distractors}
holdout_ratio: 0.0
net:
  _target_: sauce.networks.Network
  network_name: custom
  n_outputs: ${data.metadata.n_classes}
  block_type: resnet
  in_channels: ${data.metadata.n_channels}
  n_blocks: 4
  threed: true
  n_basefilters: 32
  layer_size: 2